title: Hrvatski curling savez
title_en: Croatian Curling Federation
description: Službene web stranice Hrvatskog curling saveza
description_en: Official website of the Croatian Curling Federation
url: "https://curling.hr"
baseurl: ""

# Build
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
