title: Hrvatski curling savez
description: Službene web stranice Hrvatskog curling saveza
url: "https://admin-curling-hr.github.io"
baseurl: "/curling-hr"

theme: minima

lang: hr

minima:
  author: Hrvatski curling savez

plugins:
  - jekyll-feed
  - jekyll-sitemap
